version: "3.9"

services:
  lf_psql:
    image: postgres:15
    container_name: lf_psql
    network_mode: bridge
    ports:
      - 127.0.0.1:5442:5432
    volumes:
      - /dbs/lf_psql:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lf000
  lf_api:
    image: lf_api
    container_name: lf_api
    network_mode: bridge
    volumes:
    - ./lf_api:/lf_api
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - lf_psql
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
