version: "3.9"

services:
  lf_psql:
    image: postgres:15
    container_name: lf_psql
    network_mode: bridge
    ports:
      - 127.0.0.1:5442:5432
    volumes:
      - /dbs/lf_psql:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  lf_api:
    image: lf_api
    container_name: lf_api
    network_mode: bridge
    volumes:
    - ./lf_api:/lf_api
    tty: true
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_TABLE: ${DB_TABLE}
      DB_HOST: "lf_psql"
    ports:
      - 8000:8000
    links:
      - lf_psql
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
