version: "3.9"

services:
  psql:
    image: postgres:15
    container_name: lf_psql
    network_mode: bridge
    ports:
      - 127.0.0.1:5442:5432
    volumes:
      - /dbs/lf_psql:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lf000
  server:
    image: lf_server
    container_name: lf_server
    network_mode: bridge
    volumes:
    - ./server:/lf_server
    tty: true
    depends_on:
      - psql
