version: "3.9"

services:
  psql:
    image: postgres:15
    container_name: lf_psql
    tty: true
    ports:
      - 127.0.0.1:5442:5432
    volumes:
      - /dbs/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lf000
  server:
    image: lf_server
    container_name: lf_server
    tty: true

